### ISSUE TITLE
Graphical glitching

### ISSUE THREAD

**Issue by SBBurzmali** [jaldhar/The-Girl-Who-Played-With-The-Dragons-Nest#1]
The bottom half of the screen flickers when played in a terminal window, and the whole screen flickers when played from a full screen terminal. I am using Ubuntu 13.04.
![tgwpwtdn](https://f.cloud.github.com/assets/6994243/2456354/59b78efc-af15-11e3-9956-1f815e058a2d.png)

**Comment by jaldhar** [comment]
Thank you for reporting this issue.  After a long, long, period of inactivity I've looked at this again and I believe I have fixed the problem.  I also made some cosmetic changes to the code and the build system but there remains a lot of work left to polish this game.  Hopefully I will get around to it soon.
